<?php
/**
 * Created by PhpStorm.
 * User: Pradip
 * Date: 29-07-2016
 * Time: 21:23
 */

class Location_City_Block_List extends Mage_Core_Block_Template{
    protected $_cssPath = array();
    protected $_cityCollection = null;

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_cssPath[] = array('skin_css' => 'css/state/style.css');
        $this->setTemplate('location/city/list.phtml');
    }

    public function getState(){
            $stateId = $this->getRequest()->getParam('id');
            if (!Mage::registry('current_state') && $stateId) {
                $stateInfo = Mage::getModel('state/state')->load($stateId);
                Mage::register('current_state', $stateInfo);
            }
            return Mage::registry('current_state');
    }

    public function getCityCollection(){
        try {
            if (is_null($this->_cityCollection)) {
                $stateId = $this->getRequest()->getParam('id', 0);
                $cityCollection = Mage::getModel('city/city')->getCollection();
                $cityCollection->addFieldToFilter(
                    'state_id',$stateId
                );
                $cityCollection->addFieldToFilter(
                    'status', Location_City_Model_City::STATUS_ENABLE
                );
                $cityCollection->getSelect()->order('position ASC');
                $this->_cityCollection = $cityCollection;
            }

        } catch (Exception $e) {
            Mage::log($e, null, "city_execption.log");
        }
        return $this->_cityCollection;
    }

    public function getCssJsHtml(){
        try{
            $cssJsHtml = '';
            if($this->_cssPath){
                foreach($this->_cssPath as $items){
                    foreach($items as $type => $path){
                        switch($type){
                            case 'skin_css':
                                $cssJsHtml = '<link rel="stylesheet" type="text/css" href="'.$this->getSkinUrl($path).'">';
                                break;
                        }
                    }
                }
            }
            return $cssJsHtml;
        } catch(Exception $e){
        }
    }

    public function getCityUrl($cityId = null) {
        return $this->getUrl('city/index/view', array('id'=>$cityId));
    }
}