<?php
class Location_State_Block_State extends Mage_Core_Block_Template{

    protected $_cssPath = array();
     protected function _construct()
     {
         parent::_construct(); // TODO: Change the autogenerated stub
         $this->_cssPath[] = array('skin_css' => 'css/state/style.css');
         $this->setTemplate('location/state.phtml');
     }

    public function getStateCollection(){

       return Mage::getModel('state/state')->getCollection();
    }

    public function getCssJsHtml(){

        try{
            $cssJsHtml = '';
            if($this->_cssPath){
                foreach($this->_cssPath as $items){
                    foreach($items as $type => $path){
                        switch($type){
                            case 'skin_css':
                                $cssJsHtml = '<link rel="stylesheet" type="text/css" href="'.$this->getSkinUrl($path).'">';
                                break;
                        }
                    }
                }
            }
            return $cssJsHtml;
        }
        catch(Exception $e){

        }
    }

    public function getStateUrl($stateId = null) {
        return $this->getUrl('state/index/view', array('id'=>$stateId));
    }

}