<?php
class Location_City_Block_City extends Mage_Core_Block_Template{

     protected $_cssPath = array();
     protected function _construct()
     {
         parent::_construct(); // TODO: Change the autogenerated stub
         $this->_cssPath[] = array('skin_css' => 'css/state/style.css');

         $this->setTemplate('location/city.phtml');
     }

    public function getCityInfo(){
        $stateID = $this->getRequest()->getParam('id');
        $cityCollection = Mage::getModel('city/city')->getCollection();
        $cityCollection->addFieldToFilter(
            'state_id',$stateID
        );
        $cityCollection->addFieldToFilter(
            'status', 1
        );
        $cityCollection->getSelect()->order('position ASC');
        Mage::log((string)$cityCollection->getSelect(), null, "text.log",true);
        return $cityCollection;
    }

    public function getStateInfoById(){

        $stateId = $this->getRequest()->getParam('id');
        $stateInfo = Mage::getModel('state/state')->load($stateId);

        return $stateInfo;
    }

    public function getStateInformation(){
        $stateId = $this->getRequest()->getParam('sid');
        $stateInfo = Mage::getModel('state/state')->load($stateId);

        return $stateInfo;
    }

    public function getCityInformation(){
        $cityId = $this->getRequest()->getParam('id');
        $cityInfo = Mage::getModel('city/city')->load($cityId);

        return $cityInfo;
    }

    public function getCategoryInfo(){
      $cityId = $this->getRequest()->getParam('id');
      $catCollection = Mage::getModel('store/store')->getCollection();
        $catCollection->addFieldToFilter(
            'city_id',$cityId
        );
        $catCollection->getSelect()->order('position ASC');
        
        foreach($catCollection as $catInfo){
            $catAllVal = $catInfo->getCategories();
            $stateID = $catInfo->getStateId();
            $this->getStateInformation($stateID);
            $catArray = explode(',',$catAllVal);
        }
         $table = "<ul>";
        for($i=0;$i<count($catArray);$i++){
            $catVal = $catArray[$i];
            $category = Mage::getModel('catalog/category')->load($catVal);
           // print_r($category);
            if($category->getName() !="Default Category"){
              $table .= "<li><a href='/store/store/view/sid/$stateID/cid/$catVal'>".$category->getName()."</a></li>";
            }
        }
         $table.= "</ul>";
       // Mage::log((string)$catCollection->getSelect(), null, 'text.log',true);
       return $table;
    }



    public function getCssJsHtml(){

        try{
            $cssJsHtml = '';
            if($this->_cssPath){
                foreach($this->_cssPath as $items){
                    foreach($items as $type => $path){
                        switch($type){
                            case 'skin_css':
                                $cssJsHtml = '<link rel="stylesheet" type="text/css" href="'.$this->getSkinUrl($path).'">';
                                break;
                        }
                    }
                }
            }
            return $cssJsHtml;
        }
        catch(Exception $e){

        }
    }

}