<?php
/**
 * Created by PhpStorm.
 * User: Pradip
 * Date: 29-07-2016
 * Time: 21:23
 */

class Location_Store_Block_Product extends Mage_Core_Block_Template{
    protected $_cssPath = array();
    protected $_productCollection = null;

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_cssPath[] = array('skin_css' => 'css/state/style.css');
        $this->setTemplate('location/store/product.phtml');
    }


    public function getProductCollection(){
        try {
            if (is_null($this->_productCollection)) {
                $merchantStoreId = $this->getRequest()->getParam('id', 0);
                $products = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*');
                $storeTableName = Mage::getSingleton('core/resource')->getTableName('store_info');
                $productTable = Mage::getResourceModel('catalog/product')->getEntityTable();
                $productMerchantStoreAttribute = Mage::getResourceModel('catalog/product')->getAttribute('merchant_store');
                $products->getSelect()->joinInner(
                    array('merchant_store_tbl' => $productTable.'_'.$productMerchantStoreAttribute->getBackendType()),
                    'merchant_store_tbl.entity_id = e.entity_id AND merchant_store_tbl.value IS NOT NULL AND merchant_store_tbl.attribute_id = '.
                    $productMerchantStoreAttribute->getId(),
                    array()
                );
                $products->getSelect()->Where('merchant_store_tbl.value = '.$merchantStoreId);
                $this->_productCollection = $products;
            }

        } catch (Exception $e) {
            Mage::log($e, null, "product_exception.log");
        }
        return $this->_productCollection;
    }

    public function getCssJsHtml(){
        try{
            $cssJsHtml = '';
            if($this->_cssPath){
                foreach($this->_cssPath as $items){
                    foreach($items as $type => $path){
                        switch($type){
                            case 'skin_css':
                                $cssJsHtml = '<link rel="stylesheet" type="text/css" href="'.$this->getSkinUrl($path).'">';
                                break;
                        }
                    }
                }
            }
            return $cssJsHtml;
        } catch(Exception $e){
        }
    }

    public function getCityUrl($cityId = null) {
        return $this->getUrl('city/index/view', array('id'=>$cityId));
    }
}