<?php
/**
 * Created by PhpStorm.
 * User: Pradip
 * Date: 29-07-2016
 * Time: 21:23
 */

class Location_Store_Block_List extends Mage_Core_Block_Template{
    protected $_cssPath = array();
    protected $_storeCollection = null;

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_cssPath[] = array('skin_css' => 'css/state/style.css');
        $this->setTemplate('location/store/list.phtml');
    }

    public function getState(){
            $stateId = $this->getRequest()->getParam('sid');
            if (!Mage::registry('current_state') && $stateId) {
                $stateInfo = Mage::getModel('state/state')->load($stateId);
                Mage::register('current_state', $stateInfo);
            }
            return Mage::registry('current_state');
    }

    public function getStoreCollection(){
        try {
            if (is_null($this->_storeCollection)) {
                $catId = $this->getRequest()->getParam('id', 0);
                $storeCollection = Mage::getModel('store/store')->getCollection();
                $storeCollection->addFieldToFilter('categories', array('finset' => $catId));

                $storeCollection->getSelect()->order('position ASC');
                Mage::log((string)$storeCollection->getSelect(), null, "store_execption.log",true);
                $this->_storeCollection = $storeCollection;
            }

        } catch (Exception $e) {
            Mage::log($e, null, "city_execption.log");
        }
        return $this->_storeCollection;
    }

    public function getCssJsHtml(){
        try{
            $cssJsHtml = '';
            if($this->_cssPath){
                foreach($this->_cssPath as $items){
                    foreach($items as $type => $path){
                        switch($type){
                            case 'skin_css':
                                $cssJsHtml = '<link rel="stylesheet" type="text/css" href="'.$this->getSkinUrl($path).'">';
                                break;
                        }
                    }
                }
            }
            return $cssJsHtml;
        } catch(Exception $e){
        }
    }

    public function getCityUrl($cityId = null) {
        return $this->getUrl('merchant/index/product', array('id'=>$cityId));
    }
}