<?php
/**
 * Created by PhpStorm.
 * User: Pradip
 * Date: 29-07-2016
 * Time: 21:23
 */

class Location_Store_Block_Product extends Mage_Core_Block_Template{
    protected $_cssPath = array();
    protected $_productCollection = null;

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_cssPath[] = array('skin_css' => 'css/state/style.css');
        $this->setTemplate('location/store/product.phtml');
    }


    public function getProductCollection(){
        try {
            if (is_null($this->_productCollection)) {
                $storeId = $this->getRequest()->getParam('id', 0);
                $storeCollection = Mage::getModel('catalog/product')->getCollection();
                $storeCollection->addFieldToFilter('merchant_store', $storeId)->addAttributeToSelect('*');
                $storeCollection->getSelect()->order('entity_id ASC');

                $storeProductId = array();
                foreach($storeCollection as $items){
                   $storeProductId[] = $items->getEntityId();
                    //echo "<pre>"; var_dump($items); echo "</pre>";exit;
                }

                $productCollection = Mage::getModel('catalog/product')->getCollection()
                    ->addAttributeToFilter('entity_id', array('in' => $storeProductId))->addAttributeToSelect('*');

                $productCollection->getSelect()->order("find_in_set(entity_id,'".implode(',',$storeProductId)."')");

              // Mage::log((string)$productCollection->getSelect(), null, 'sql.log',true);
                $this->_productCollection = $productCollection;
            }

        } catch (Exception $e) {
            Mage::log($e, null, "product_exception.log");
        }
        return $this->_productCollection;
    }

    public function getCssJsHtml(){
        try{
            $cssJsHtml = '';
            if($this->_cssPath){
                foreach($this->_cssPath as $items){
                    foreach($items as $type => $path){
                        switch($type){
                            case 'skin_css':
                                $cssJsHtml = '<link rel="stylesheet" type="text/css" href="'.$this->getSkinUrl($path).'">';
                                break;
                        }
                    }
                }
            }
            return $cssJsHtml;
        } catch(Exception $e){
        }
    }

    public function getCityUrl($cityId = null) {
        return $this->getUrl('city/index/view', array('id'=>$cityId));
    }
}