<?php
class Location_Store_Block_Store extends Mage_Core_Block_Template{

    protected $_cssPath = array();
     protected function _construct()
     {
         parent::_construct(); // TODO: Change the autogenerated stub
         $this->_cssPath[] = array('skin_css' => 'css/state/style.css');

         $this->setTemplate('location/store.phtml');
     }

    public function getStoreInfo(){
      $catId = $this->getRequest()->getParam('cid');
      $storeCollection = Mage::getModel('store/store')->getCollection();
        /*$storeCollection->addFieldToFilter(
            'categories IN',  $catId
        );*/
       $storeCollection->addFieldToFilter('categories', array('finset' => $catId));
      // Mage::log((string)$storeCollection->getSelect(),null,'text.log',true) ;
       return $storeCollection;
    }
    public function getStateInformation(){
        $stateId = $this->getRequest()->getParam('sid');
        $stateInfo = Mage::getModel('state/state')->load($stateId);

        return $stateInfo;
    }

    public function getCssJsHtml(){

        try{
            $cssJsHtml = '';
            if($this->_cssPath){
                foreach($this->_cssPath as $items){
                    foreach($items as $type => $path){
                        switch($type){
                            case 'skin_css':
                                $cssJsHtml = '<link rel="stylesheet" type="text/css" href="'.$this->getSkinUrl($path).'">';
                                break;
                        }
                    }
                }
            }
            return $cssJsHtml;
        }
        catch(Exception $e){

        }
    }

}